- name: "copy hadoop software"
  copy:
          dest: "/root"
          src: "{{ hadoop_pkg  }}"
- name: "copy java software"
  copy:
          dest: "/root"
          src: "{{ java_pkg  }}"

- name: "install java"
  package:
          name: "{{ java_pkg  }}"

          #- name: "install hadoop"
  #        ignore_errors: yes
  #command: "rpm -i hadoop-1.2.1-1.x86_64.rpm --force"
- name: "2nd way hadoop installtion"
  ignore_errors: yes
  package:
          name: "{{ hadoop_pkg }}"

- name: "configure mapred-site.xml file"
  template:
                 src: "mapred.j2"
                 dest: "/etc/hadoop/mapred-site.xml"

- name: "configure core-site.xml file"
  template:
                 src: "core-site3.yml"
                 dest: "/etc/hadoop/core-site.xml"
